Document: bencode-tools
Title: Debian bencode-tools Manual
Author: <insert document author here>
Abstract: This manual describes what bencode-tools is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bencode-tools/bencode-tools.sgml.gz

Format: postscript
Files: /usr/share/doc/bencode-tools/bencode-tools.ps.gz

Format: text
Files: /usr/share/doc/bencode-tools/bencode-tools.text.gz

Format: HTML
Index: /usr/share/doc/bencode-tools/html/index.html
Files: /usr/share/doc/bencode-tools/html/*.html
